### PR TITLE
Open a survey underneath the consent form

### LINKED ISSUE #193: After clicking on "What is this ?", user is not able to participate in the survey.
OS : Mac 10.9.5
Chrome Version : 44.0.2363.0 canary

Steps to reproduce the issue:
1) Add the CUES extension
2) Navigate to SSL warning/malware warning/phishing warning
3) Survey notification window shows up
4) Click on the What's is this ?
5) CUES survey details page opens up.

Actual Result:
User can not participate in the Survey for that session./Page.

Expected Result:
User should have option in the page if he wants participate in the survey. 

screen shot 2015-04-10 at 4 47 22 pm

### PR DESCRIPTION
**Pull request by adrifelt**
When someone clicks on the "What is this?" notification button, we should also open a survey (but in the tab underneath it).

This PR changes loadSurvey to return a promise that resolves when the survey is done opening. That way we can guarantee that the consent form opens on top of the consent form. Otherwise, there is a race condition for which one opens on top.

Fixes #193

### CODE REVIEW

File: extension/background.js [hunk 1]
```diff
@@ -351,71 +354,78 @@ function showSurveyNotification(element, decision) {
...
+              constants.SurveyLocation.PHISHING_NOPROCEED;
+          visitUrl = urlHandler.GetMinimalUrl(element['destination']);
+          break;
+        case constants.EventType.EXTENSION_INSTALL:
+        case constants.EventType.EXTENSION_INLINE_INSTALL:
+        case constants.EventType.EXTENSION_BUNDLE:
+          surveyUrl = userDecision === constants.DecisionType.PROCEED ?
+              constants.SurveyLocation.EXTENSION_PROCEED :
+              constants.SurveyLocation.EXTENSION_NOPROCEED;
+          break;
```
Comment (meacer) [inline extension/background.js]: Just to double check, you don't need the visitUrl for extension installs, right?

**Comment by meacer** [comment]
Lgtm

File: extension/background.js (hunk 1 above)
Comment (adrifelt) [inline extension/background.js]: thanks for checking. no, there's no visitUrl for extension installs, it's handled below w/o the visit url.
