### PR TITLE
Fix survey submission bug

### LINKED ISSUE #118: Delayed form submission not working sometimes
screen shot 2014-11-26 at 10 50 13 am

### PR DESCRIPTION
**Pull request by adrifelt**
The backend expects that all of the "answer" fields will be a string, but these values are booleans. Converting them to strings to avoid rejection.

Fixes #118

### CODE REVIEW

**Comment by meacer** [comment]
Lgtm

File: extension/background.js [hunk 1]
```diff
@@ -509,9 +509,9 @@ function recordEvent(element, decision) {
   responses.push(new SurveySubmission.Response(
       'Response', decision['name']));
   responses.push(new SurveySubmission.Response(
-      'Details', decision['details']));
+      'Details', decision['details'].toString()));
```
Comment (meacer) [inline extension/background.js]: Does the SurveySubmission.Response expect the second param to be a string? Maybe you could add a check in the constructor (there and wherever applicable).

Comment (adrifelt) [inline extension/background.js]: Good call, added a check in the constructor.
